# main text of home
url: https://www.leishi.io
# For display purpose
domain_name: "leishi.io"
domain_description: "This domain is for sale!"
email: me@leishi.io

# If you want to put some external links
external_links:
    - url: "https://www.leishi.io/"
      name: "Lei Shi"
    - url: "https://blog.leishi.io/"
      name: "blog"
    - url: "https://2cn.io/"
      name: "2cn.io"
    - url: "https://189.io/"
      name: "189.io"
    - url: "https://yuehu.io/"
      name: "yuehu.io"
    - url: "https://zigbee.io/"
      name: "zigbee.io"
    - url: "https://kikfm.io/"
      name: "kikfm.com"
    - url: "https://www.lowercamelcase.com/"
      name: "lowerCamelCase.com"

# if it's an external image, update below for true
# better with square images
external-image: false
picture: assets/images/profile.jpg


# To enable google analytics, supply your token below
analytics-google: 'UA-119177383-5'

# To enable piwik tracking, supply your url & site ID below
# analytics-piwik-url: 'piwik.my-host.com'
# analytics-piwik-id: 1

# do you want a larger site? change the option below
# options: [normal, large] | default: normal
# normal = 560px / large = 810px
width: normal

# do you want some animations?
animation: true

plugins:
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-admin

jekyll-mentions:
    base_url: https://github.com

compress_html:
    ignore:
        envs:
        - development
        - stage

exclude: ["travis.sh", "Rakefile", "README.md", "screenshot.png", "Gemfile", "Gemfile.lock", "FAQ.md", "vendor"]
